{{- if .Values.abTesting.enabled }}
{{- $fullName := include "shopifake-gateway-chart.fullname" . }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ $fullName }}
spec:
  host: {{ $fullName }}
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
{{- end }}
