{{- if .Values.gateway.enabled }}
{{- $fullName := include "shopifake-gateway-chart.fullname" . }}
{{- $servicePort := .Values.service.port | default 80 }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $fullName }}
spec:
  hosts:
    - {{ .Values.gateway.host | quote }}
  gateways:
    - {{ $fullName }}
  http:
    {{- range $index, $route := .Values.gateway.routes }}
      {{- $matches := $route.match | default (list (dict "uri" (dict "prefix" "/"))) }}
    {{- $destination := $route.destination | default (dict) }}
    {{- $destHost := $destination.host | default $fullName }}
    {{- $destPort := $destination.port | default $servicePort }}
    - name: {{ default (printf "route-%d" (add $index 1)) $route.name }}
      match:
{{ toYaml $matches | indent 8 }}
      {{- if $route.rewrite }}
      rewrite:
{{ toYaml $route.rewrite | indent 8 }}
      {{- end }}
      route:
        - destination:
            host: {{ $destHost }}
            {{- with $destination.subset }}
            subset: {{ . }}
            {{- end }}
            {{- if $destPort }}
            port:
              number: {{ $destPort }}
            {{- end }}
          {{- with $route.weight }}
          weight: {{ . }}
          {{- end }}
    {{- end }}
    {{- if .Values.abTesting.enabled }}
    - name: gateway-ab-test
      route:
        - destination:
            host: {{ $fullName }}
            subset: v1
          weight: {{ .Values.abTesting.v1Weight }}
        - destination:
            host: {{ $fullName }}
            subset: v2
          weight: {{ .Values.abTesting.v2Weight }}
    {{- else }}
    - name: gateway-default
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ $fullName }}
            port:
              number: {{ $servicePort }}
    {{- end }}
{{- end }}
